# -*- coding: utf-8 -*-
"""proyect.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16n9VGns8tdi8FuBcYlZ60z59r1KR-2zY
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix


# -----------------------------------------------------
# CARGAR DATASET
# -----------------------------------------------------
st.title("🌸 Iris Species Classification – Dashboard Interactivo")

df = pd.read_csv("Iris.csv")
df = df.drop(columns=["Id"])   # igual que en tu notebook

numeric_cols = ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]

# Codificar especies
le = LabelEncoder()
df["Species_cod"] = le.fit_transform(df["Species"])


# -----------------------------------------------------
# PREPROCESAMIENTO (igual al notebook)
# -----------------------------------------------------
X = df[numeric_cols]
y = df["Species_cod"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# -----------------------------------------------------
# ENTRENAMIENTO DEL MODELO
# -----------------------------------------------------
model = RandomForestClassifier(n_estimators=200, random_state=42)
model.fit(X_train_scaled, y_train)


# -----------------------------------------------------
# MENÚ DE PÁGINAS
# -----------------------------------------------------
menu = st.sidebar.radio(
    "Navegación",
    ["📊 Métricas del Modelo", "📈 Visualizaciones", "🔮 Predicción del Usuario"]
)


# -----------------------------------------------------
# 📊 MÉTRICAS DEL MODELO
# -----------------------------------------------------
if menu == "📊 Métricas del Modelo":
    st.header("📊 Métricas del Modelo")

    y_pred = model.predict(X_test_scaled)

    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="weighted")
    recall = recall_score(y_test, y_pred, average="weighted")
    f1 = f1_score(y_test, y_pred, average="weighted")

    st.write(f"**Accuracy:** {accuracy:.4f}")
    st.write(f"**Precision:** {precision:.4f}")
    st.write(f"**Recall:** {recall:.4f}")
    st.write(f"**F1 Score:** {f1:.4f}")

    st.subheader("Matriz de Confusión")
    cm = confusion_matrix(y_test, y_pred)

    fig, ax = plt.subplots(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=le.classes_,
                yticklabels=le.classes_)
    st.pyplot(fig)


# -----------------------------------------------------
# 📈 VISUALIZACIONES
# -----------------------------------------------------
elif menu == "📈 Visualizaciones":
    st.header("📈 Visualizaciones del dataset")

    st.subheader("Histogramas")
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    axes = axes.flatten()

    for i, col in enumerate(numeric_cols):
        axes[i].hist(df[col], bins=15, edgecolor="black")
        axes[i].set_title(f"Histograma de {col}")

    st.pyplot(fig)

    st.subheader("Gráfico 3D del Dataset")

    fig3d = px.scatter_3d(
        df,
        x="PetalLengthCm",
        y="PetalWidthCm",
        z="SepalLengthCm",
        color="Species",
        title="Dataset Iris – Visualización 3D"
    )
    st.plotly_chart(fig3d)



# -----------------------------------------------------
# 🔮 PREDICCIÓN DEL USUARIO
# -----------------------------------------------------
elif menu == "🔮 Predicción del Usuario":
    st.header("🔮 Predicción de Especie")

    sl = st.number_input("Sepal Length (cm)", 0.0, 10.0, 5.0)
    sw = st.number_input("Sepal Width (cm)", 0.0, 10.0, 3.5)
    pl = st.number_input("Petal Length (cm)", 0.0, 10.0, 1.4)
    pw = st.number_input("Petal Width (cm)", 0.0, 10.0, 0.2)

    if st.button("Predecir"):
        new_data = np.array([[sl, sw, pl, pw]])
        new_data_scaled = scaler.transform(new_data)
        pred = model.predict(new_data_scaled)[0]
        pred_name = le.inverse_transform([pred])[0]

        st.success(f"🌼 La especie predicha es: **{pred_name}**")

        # Gráfico 3D mostrando el punto nuevo
        df_aux = df.copy()
        df_aux["Tipo"] = "Dataset"

        new_point = pd.DataFrame({
            "PetalLengthCm": [pl],
            "PetalWidthCm": [pw],
            "SepalLengthCm": [sl],
            "Species": [pred_name],
            "Tipo": ["Nuevo Punto"]
        })

        df_plot = pd.concat([df_aux, new_point])

        fig_pred = px.scatter_3d(
            df_plot,
            x="PetalLengthCm",
            y="PetalWidthCm",
            z="SepalLengthCm",
            color="Tipo",
            symbol="Tipo",
            title="Posición del Punto Predicho"
        )
        st.plotly_chart(fig_pred)